name: Build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main      

jobs:
  build: # make sure build/ci work properly
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
        name: Get the sources
      - run: npm ci
        name: restore dependencies
      - run: npm run all
        name: Build